# Change these first
owner: lirc572 # Your GitHub organization or username, where this repository lives
repo: "Status.Paimon.Chat" # The name of this repository

sites:
  - name: Paimon Chat
    url: https://paimon.chat

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.paimon.chat
  # baseUrl: /your-repo-name
  logoUrl: https://paimon.chat/favicon.ico
  favicon: https://paimon.chat/favicon.ico
  name: Paimon Chat Status
  introTitle: "**[Paimon Chat](https://paimon.chat)** -- Your best travelling companion~"
  introMessage: This is the status page for [Paimon Chat](https://paimon.chat)
  navbar:
    - title: Home
      href: https://paimon.chat
    - title: Status
      href: /

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
